In [2]:
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from rich import print as print
import torch
from torch import nn
from tqdm.autonotebook import tqdm

/tmp/ipykernel_76788/4250047004.py:6: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

In [3]:
X,y = fetch_california_housing(
    return_X_y=True,
    as_frame=True
)
display(X)
display(y)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [4]:
X.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='str')

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

display(X_train)
display(X_test,)
display(y_train)
display(y_test)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
14196,3.2596,33.0,5.017657,1.006421,2300.0,3.691814,32.71,-117.03
8267,3.8125,49.0,4.473545,1.041005,1314.0,1.738095,33.77,-118.16
17445,4.1563,4.0,5.645833,0.985119,915.0,2.723214,34.66,-120.48
14265,1.9425,36.0,4.002817,1.033803,1418.0,3.994366,32.69,-117.11
2271,3.5542,43.0,6.268421,1.134211,874.0,2.300000,36.78,-119.80
...,...,...,...,...,...,...,...,...
11284,6.3700,35.0,6.129032,0.926267,658.0,3.032258,33.78,-117.96
11964,3.0500,33.0,6.868597,1.269488,1753.0,3.904232,34.02,-117.43
5390,2.9344,36.0,3.986717,1.079696,1756.0,3.332068,34.03,-118.38
860,5.7192,15.0,6.395349,1.067979,1777.0,3.178891,37.58,-121.96
15795,2.5755,52.0,3.402576,1.058776,2619.0,2.108696,37.77,-122.42

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20046,1.6812,25.0,4.192201,1.022284,1392.0,3.877437,36.06,-119.01
3024,2.5313,30.0,5.039384,1.193493,1565.0,2.679795,35.14,-119.46
15663,3.4801,52.0,3.977155,1.185877,1310.0,1.360332,37.80,-122.44
20484,5.7376,17.0,6.163636,1.020202,1705.0,3.444444,34.28,-118.72
9814,3.7250,34.0,5.492991,1.028037,1063.0,2.483645,36.62,-121.93
...,...,...,...,...,...,...,...,...
15362,4.6050,16.0,7.002212,1.066372,1351.0,2.988938,33.36,-117.22
16623,2.7266,28.0,6.131915,1.256738,1650.0,2.340426,35.36,-120.83
18086,9.2298,25.0,7.237676,0.947183,1585.0,2.790493,37.31,-122.05
2144,2.7850,36.0,5.289030,0.983122,1227.0,2.588608,36.77,-119.76
3665,3.5521,17.0,3.988839,1.033482,1671.0,3.729911,34.22,-118.37

14196    1.030
8267     3.821
17445    1.726
14265    0.934
2271     0.965
         ...
11284    2.292
11964    0.978
5390     2.221
860      2.835
15795    3.250
Name: MedHouseVal, Length: 16512, dtype: float64

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: MedHouseVal, Length: 4128, dtype: float64

In [7]:

standardScalar = StandardScaler()
X_train_non_scalar = X_train.copy()
X_train = standardScalar.fit_transform(X_train)

# standardScalar.transform(X_test)

In [8]:

print(standardScalar.mean_)


X_test = standardScalar.transform(X_test)

print(X_test[-1].max(), X_test[-1].min())

[ 3.88075426e+00  2.86082849e+01  5.43523502e+00  1.09668475e+00
  1.42645300e+03  3.09696119e+00  3.56431492e+01 -1.19582290e+02]

0.6044549279679836 -0.9211376319710946

In [9]:
X_train_tensor = torch.tensor(X_train,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.to_numpy(),dtype=torch.float32).reshape(-1,1)
y_test_tensor  = torch.tensor(y_test.to_numpy(),dtype=torch.float32).reshape(-1,1)

In [10]:
print(
    X_train_tensor,
    X_test_tensor,
    y_train_tensor,
    y_test_tensor
)

tensor([[-0.3262,  0.3485, -0.1749,  ...,  0.0514, -1.3728,  1.2726],
        [-0.0358,  1.6181, -0.4028,  ..., -0.1174, -0.8767,  0.7092],
        [ 0.1447, -1.9527,  0.0882,  ..., -0.0323, -0.4601, -0.4476],
        ...,
        [-0.4970,  0.5865, -0.6068,  ...,  0.0203, -0.7550,  0.5995],
        [ 0.9655, -1.0798,  0.4022,  ...,  0.0071,  0.9065, -1.1855],
        [-0.6854,  1.8562, -0.8514,  ..., -0.0854,  0.9954, -1.4149]]) tensor([[-1.1551, -0.2863, -0.5207,  ...,
0.0674,  0.1951,  0.2853],
        [-0.7087,  0.1104, -0.1658,  ..., -0.0360, -0.2355,  0.0610],
        [-0.2104,  1.8562, -0.6108,  ..., -0.1500,  1.0095, -1.4249],
        ...,
        [ 2.8090, -0.2863,  0.7550,  ..., -0.0265,  0.7801, -1.2304],
        [-0.5754,  0.5865, -0.0612,  ..., -0.0439,  0.5274, -0.0886],
        [-0.1726, -0.9211, -0.6059,  ...,  0.0547, -0.6661,  0.6045]]) tensor([[1.0300],
        [3.8210],
        [1.7260],
        ...,
        [2.2210],
        [2.8350],
        [3.2500]]) tensor([[0.4770],
        [0.4580],
        [5.0000],
        ...,
        [5.0000],
        [0.7230],
        [1.5150]])

In [11]:
print(X_train_tensor.shape,y_train_tensor.shape)

torch.Size([16512, 8])
torch.Size([16512, 1])

In [12]:
class RegressionANN(nn.Module):

    def __init__(self):
        super(RegressionANN,self).__init__()

        self.hidden_layer = nn.Linear(8,16)

        self.relu = nn.ReLU()
        self.output_layer = nn.Linear(16,1)

    def forward(self,x):
        x = self.hidden_layer(x)
        x = self.relu(x)
        x = self.output_layer(x)

        return x

In [13]:
torch.manual_seed(42)
model = RegressionANN()
print(model)
print(model.output_layer.bias)

RegressionANN(
  (hidden_layer): Linear(in_features=8, out_features=16, bias=True)
  (relu): ReLU()
  (output_layer): Linear(in_features=16, out_features=1, bias=True)
)

Parameter containing:
tensor([0.2272], requires_grad=True)

In [14]:
criterion = nn.MSELoss()
print(criterion)

MSELoss()

In [15]:
optim = torch.optim.Adam(params=model.parameters(),lr=0.01)
print(optim)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

In [16]:
model

RegressionANN(
  (hidden_layer): Linear(in_features=8, out_features=16, bias=True)
  (relu): ReLU()
  (output_layer): Linear(in_features=16, out_features=1, bias=True)
)

In [17]:
predictions = model(X_train_tensor)
loss = criterion(predictions, y_train_tensor)

print(loss.item())

4.202902793884277

In [18]:
# training the model 

epochs = 100

for epoch in tqdm(range(epochs)):
    optim.zero_grad()
    predictions = model(X_train_tensor)

    loss = criterion(predictions,y_train_tensor)

    loss.backward()
    optim.step()

    # if (epoch + 1) % 10 == 0:
    #     print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

print("Final loss after 100 iterations:", loss.item())

100%|██████████| 100/100 [00:00<00:00, 123.63it/s]

Final loss after 100 iterations: 0.47498002648353577

In [27]:
class RegressionANN64(nn.Module):


    def __init__(self):


        super(RegressionANN64,self).__init__()


        self.input = nn.Linear(8,64)
        self.output = nn.Linear(64, 8 )

        self.relu = nn.ReLU()



    def forward(self,x):

        x = self.input(x)
        x = self.relu(x)

        x = self.output(x)


        return x

model64 = RegressionANN64()

print(model64)

RegressionANN64(
  (input): Linear(in_features=8, out_features=64, bias=True)
  (output): Linear(in_features=64, out_features=8, bias=True)
  (relu): ReLU()
)

In [28]:
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model64.parameters(), lr=0.01)


print(optimizer)
print(criterion)

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)

MSELoss()

In [30]:
epochs = 10000

for epoch in tqdm(range(epochs)):

    optimizer.zero_grad()
    predictions = model64(X_train_tensor)

    loss = criterion(predictions, y_train_tensor)
    loss.backward()

    optimizer.step()


print("Final loss after 100 iterations (64 neurons):", loss.item())

100%|██████████| 10000/10000 [00:37<00:00, 270.01it/s]

Final loss after 100 iterations (64 neurons): 0.2358388602733612